# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  def update_version(options)
    if options[:version]
      version = options[:version]
    else
      version = prompt(text: "Enter version (e.g., 1.0.0) or 'skip' to only increment build number: ")
    end

    if version.downcase == 'skip'
      puts "Skipping version update, only incrementing build number."
    else
      re = /\d+.\d+.\d+/
      version_num = version[re, 0]

      if version_num
        increment_version_number(version_number: version_num)
        UI.message("Version number updated to #{version_num}")
      elsif ['major', 'minor', 'patch'].include?(version)
        increment_version_number(bump_type: version)
        new_version = get_version_number(xcodeproj: "LuckKids.xcodeproj")
        UI.message("Version number bumped to #{new_version} (#{version})")
      else
        UI.user_error!("[ERROR] Invalid version format!")
      end
    end
  end

  def update_build_number
    current_build = get_build_number(xcodeproj: "LuckKids.xcodeproj")
    new_build = current_build.to_i + 1
    increment_build_number(build_number: new_build, xcodeproj: "LuckKids.xcodeproj")
    UI.message("Build number incremented from #{current_build} to #{new_build}")
  end

  def notify_slack(success, lane, version, build)
    if success
      message = "새로운 LuckKids 빌드가 TestFlight에 성공적으로 업로드되었습니다! :rocket:\n버전: #{version}\n빌드: #{build}\n레인: #{lane}"
      slack(
        message: message,
        success: true,
        slack_url: ENV["SLACK_WEBHOOK_URL"]
      )
    else
      message = "LuckKids 빌드 업로드에 실패했습니다. :x:\n버전: #{version}\n빌드: #{build}\n레인: #{lane}"
      slack(
        message: message,
        success: false,
        slack_url: ENV["SLACK_WEBHOOK_URL"]
      )
    end
  end

  desc "Push a new beta build to TestFlight with version prompt"
  lane :beta do |options|
    cert
    sigh(force: true)
    update_version(options)
    update_build_number
    build_app(workspace: "LuckKids.xcworkspace", scheme: "LuckKids")
    upload_to_testflight

    version = get_version_number(xcodeproj: "LuckKids.xcodeproj")
    build = get_build_number(xcodeproj: "LuckKids.xcodeproj")
    # notify_slack(true, "beta", version, build)
  rescue => ex
    version = get_version_number(xcodeproj: "LuckKids.xcodeproj")
    build = get_build_number(xcodeproj: "LuckKids.xcodeproj")
    # notify_slack(false, "beta", version, build)
    raise ex
  end

  desc "Push a new beta build to TestFlight, only incrementing build number"
  lane :beta_build_only do
    cert
    sigh(force: true)
    update_build_number
    build_app(workspace: "LuckKids.xcworkspace", scheme: "LuckKids")
    upload_to_testflight

    version = get_version_number(xcodeproj: "LuckKids.xcodeproj")
    build = get_build_number(xcodeproj: "LuckKids.xcodeproj")
    # notify_slack(true, "beta_build_only", version, build)
  rescue => ex
    version = get_version_number(xcodeproj: "LuckKids.xcodeproj")
    build = get_build_number(xcodeproj: "LuckKids.xcodeproj")
    # notify_slack(false, "beta_build_only", version, build)
    raise ex
  end
end